import { CustomError } from 'ts-custom-error';

/**
 * The following error codes can be thrown by the dapp connector.
 */
const ErrorCodes = {
    /** The dapp connector wasn't able to process the request */
    InternalError: 'InternalError',
    /** The user rejected the request */
    Rejected: 'Rejected',
    /** Can be thrown in various circumstances, e.g. one being a malformed transaction */
    InvalidRequest: 'InvalidRequest',
};
/**
 * Whenever there's a function called that returns a promise,
 * an error with the shape can be thrown.
 */
class APIError extends CustomError {
    /** The code of the error that's thrown */
    code;
    /** The reason the error is thrown */
    reason;
    constructor(code, reason) {
        super();
        this.code = code;
        this.reason = reason;
    }
}

export { APIError, ErrorCodes };
//# sourceMappingURL=index.mjs.map
